name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      
    - name: Logged in Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Docker Images
      run: |
        services=("users-service" "login-service" "purchase-service")
        
        for service in "${services[@]}"
        do
          if [ -d "$service" ]; then
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
          else
            echo "Failed to find the directory path for service $service"
            exit 1
          fi
        done

    - name: Clean up Previous Containers
      run: |
        docker-compose down

    - name: Execute Docker Compose
      run: |
        docker-compose up -d
    - name: Deploy Docker to AWS (EC2)
      uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
        AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
        AWS_EC2_KEY: ${{ secrets.AWS_EC2_KEY }}
        DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/your-image:latest
        DOCKER_CONTAINER_NAME: your-container-name
